name: Release RShell

on:
  push:
    tags:
      - "v*.*.*"   # triggers on tags like v0.1.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build release binary
        run: cargo build --release

      - name: Prepare artifact folder
        run: mkdir -p artifacts

      - name: Copy and rename binary
        run: |
          OS=${{ matrix.os }}
          VERSION=${GITHUB_REF#refs/tags/}
          if [ "$OS" == "windows-latest" ]; then
            cp target/release/rshell.exe artifacts/rshell-$VERSION-windows.exe
          elif [ "$OS" == "macos-latest" ]; then
            cp target/release/rshell artifacts/rshell-$VERSION-macos
          else
            cp target/release/rshell artifacts/rshell-$VERSION-linux
          fi

      - name: Create GitHub Release
        id: gh_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
